AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.

Resources:
  lig-entry:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lig-show-help
      Handler: lambda_function.lambda_handler
      CodeUri: ./
      Runtime: python3.8
      AutoPublishAlias: live
      MemorySize: 128
      Timeout: 30
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        lig-entry-api:
          Type: Api
          Properties:
            Path: /
            Method: post
      Environment:
        Variables:
          REGION: ap-northeast-1
